language: node_js
node_js:
  - "node"
  - "11"
  - "10"
  - "8"

before_install:
  - yarn global add greenkeeper-lockfile@1
  - export PATH=$PATH:`yarn global bin`

before_script:
  - greenkeeper-lockfile-update
  - greenkeeper-lockfile-upload

script:
  - yarn build
  - yarn test
